name: Conda deployment

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.8, 3.9]
    name: Python ${{ matrix.python-version }} at ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        name: Conda setup
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: standard
          auto-activate-base: false
      - name: Set up libmamba solver
        shell: bash -l {0}
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
      - name: Install conda-build
        shell: bash -l {0}
        run: conda install conda-build
      - name: Install anaconda-client
        shell: bash -l {0}
        run: conda install anaconda-client
      - name: Configurate conda-build
        shell: bash -l {0}
        run: conda config --set anaconda_upload yes
      - name: Configurate conda-client from anaconda
        shell: bash -l {0}
        run: anaconda login --hostname peleffy144_3host${{ matrix.python-version }}${{ matrix.os }} --username ${{ secrets.ANACONDA_USER }} --password ${{ secrets.ANACONDA_PASSWD }}
      - name: Deploy package to conda
        shell: bash -l {0}
        run: conda build 'devtools/conda' -c conda-forge -c nostrumbiodiscovery
      - name: Logout from anaconda
        shell: bash -l {0}
        run: anaconda logout
